add k8s deploy
Knawat/knawat-moleculer-template pull request #16
Opened 2021-02-09 13:16 UTC by Mhm0ud

## :memo: Description

In this PR, we created a sample deployment to Kubernetes 

### :dart: Relevant issues

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-02-10 09:56 UTC, HazemKhaled requested changes

2021-02-10 09:56 UTC, HazemKhaled commented on deploy/k8s/k8s.yaml
> +#########################################################
split files to
k8s.yaml for generic configs, ingreese, autosclae ... etc
api.service.deployment.yaml for api service and api deployment
products.service.deployment.yaml

2021-02-10 09:56 UTC, HazemKhaled commented on deploy/k8s/k8s.yaml
> +  revisionHistoryLimit: 0
make this 3

2021-02-10 09:56 UTC, HazemKhaled commented on deploy/k8s/k8s.yaml
> +  name: api
add type to our naming convention 

ex: api-service, api-deployment

2021-02-10 09:56 UTC, HazemKhaled commented on deploy/k8s/k8s.yaml
> +  selector:
do we need this selector, or shall service only has the selector

2021-02-10 09:56 UTC, HazemKhaled commented on deploy/k8s/k8s.yaml
> +                name: common-env
Can't we load the secret here all in one lint like confgiMapRef

2021-02-10 09:56 UTC, HazemKhaled commented on README.md
> +-  `kubectl create secret generic mysecret --from-env-file=.secret`: Create a secret contains variable like users and passworda and connection string
Add more detailed readme https://gist.github.com/tobydeh/0aa33a5b672821f777165159b6a22cc5

2021-02-10 11:51 UTC, Mhm0ud commented on deploy/k8s/k8s.yaml
> +  revisionHistoryLimit: 0
I removed it because the default number is 10.

2021-02-25 12:18 UTC, closed without merging

2021-02-25 12:19 UTC, Mhm0ud commented
old one